name: PolymathGrid
favicon: null
layout_spectrum: 0.74875
typography_spectrum: 0.24958
title: Polymath Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#0046bf'
    - '#0076d6'
    - '#80b2e3'
  brandStrength: 0.875
  lightness: 0.125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
