name: PolymathGrid
favicon: null
layout_spectrum: 0.698192813899368
typography_spectrum: 0.027040250366553664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2705444742459804
  lightness: 0.5544457123614848
  saturation: 0.4189307205379009
  rhythmicContrast: 0.26346856099553406
purpose: []
